### ISSUE TITLE
How to use it ? 

### ISSUE THREAD

**Issue by m4rten** [pierosavi/pierosavi-imageit-panel#10]
Hi,

is there any tutorial how to add data to an picture ? do i need an additional plugin ? i dont know how to do it and didnt found any help.

**Comment by pierosavi** [comment]
Hello, 
you don't need any additional plugin
first you need to have a direct url to the image to use as background, then you need a data source to get data from.
You need to add a Sensor and connect the data source giving it the same alias name 

Please let me know where it isn't clear

**Comment by m4rten** [comment]
My Config:

Overview
https://s17.directupload.net/images/190528/jc9v4x7q.jpg
Metrics
https://s17.directupload.net/images/190528/byu6eoeu.png
Sensor
https://s17.directupload.net/images/190528/a7985aqa.png

ive pushed a numeric value to influxdb. it arrives 
https://s17.directupload.net/images/190528/8sr39jmf.png

**Comment by Satforst** [comment]
Hello,
I have also problems with the adding data to plugin.  Sensor and Value mappings I have set according the picture in attached screenshots. Value mappings are set to NAME column = 1, which 1 is data saved in column.
![Capture10](https://user-images.githubusercontent.com/33480055/58540782-58046180-81fa-11e9-82fb-1c9d7740af7c.PNG)
![Capture11](https://user-images.githubusercontent.com/33480055/58540788-5b97e880-81fa-11e9-8443-d624ec41dfc6.PNG)
SQL query is:
`SELECT
  $__timeEpoch(Time),
  CAST(Status AS INT) AS STATUS,
  CAST(Run AS INT) AS RUN,
  CAST(Error AS INT) AS ERROR
FROM
  MachineDataPerMinute
WHERE
  $__timeFilter(Time) AND Machine LIKE 'Name of machine in table'
ORDER BY
  Time ASC`
If I go to Explore I see all data which I need in table, but nothing change in ImageIt.
Do you have any idea how to show data in plugin?

**Comment by pierosavi** [comment]
@m4rten 
You don't need to build the plugin as I always build it myself before pushing a release, but if you want you have to install grunt as global, then `npm i` and `grunt`

What I see you and @Satforst  are missing is checking the "Render Value" checkbox to see the value

**Comment by Satforst** [comment]
@pierosavi When I check Render Value that show me only -NaN btw. I hope show only diffrent background without any value.

**Comment by pierosavi** [comment]
@Satforst I think I got now what you are trying to do, unfortunately as of right now you can't consider multiple values in a sensor so, in this case, you would need to set two different sensor for each machine, one for ERROR and one for RUN, then give a color mapping each

**Comment by Satforst** [comment]
@pierosavi The values will be always RUN or ERROR, never will be both values in 1 (I have in columns only 1 and 0 in dependies if machine running or is in the error).
Anyway I tried split machine on two sensor and still nothing.
Just for case:
From sql query I get Value Color Mappings and I take to Sensor any name then I add Value Mappings to sensor. Then shoud work fine everything, or is inthere some additional step??

**Comment by pierosavi** [comment]
If you can't have both values on 1 you can try this:

- only SELECT ONE of them (for example Error) in your query

- try to check "render value" until it shows either 0 or 1 on your sensor

- on the value mapping on the three fields set:

ERROR - = - 1 -> background color: red
OK - = - 0 -> background color: green

The first field is just the name of the mapping rule, not the field to consider, it's just to know what the rule means

**Comment by m4rten** [comment]
nice, now the values are shown ! Thanks 👍  :)

**Comment by Satforst** [comment]
I tried get to query only one of them and still nothing.
Now I thinking if is it ok format query as a Time series instead of as a table?

**Comment by pierosavi** [comment]
@Satforst I think you should try
I only use InfluxDB so I don't really know the best setup for your sql but by checking the Render Value box you can try changing things until you see 0 or 1 :)

**Comment by pierosavi** [comment]
@Satforst do you have any news?

**Comment by Satforst** [comment]
Now I don´t have any news, but I would like to try install InfluxDB, get data from my mysql database to InfluxDB and show data in Grafana. After this I post here my experience with this test.

**Comment by Satforst** [comment]
@pierosavi OK so I tested install InfluxDB, put some sample data to db then create ImageIT with this data and still nothing. I see data in explore mode and also in Inspector Query. But in sensor is still as a Value -NaN.
![InfluxDB01](https://user-images.githubusercontent.com/33480055/58950560-5e14b800-878f-11e9-9cc3-c58aed75a808.PNG)
![INfluxDB02](https://user-images.githubusercontent.com/33480055/58950563-5fde7b80-878f-11e9-8b3e-43a828e27b86.PNG)

**Comment by pierosavi** [comment]
@Satforst You need to set an alias in the "ALIAS BY" metric field and put the SAME alias on the sensor Name field

**Comment by Satforst** [comment]
@pierosavi I can`t believe it. It works!!! 
Thank you some much for your willingness :)

**Comment by AlbaColet** [comment]
@pierosavi  Hi, I am using the grafana version 6.7.3 and I can not link the sensors to metrics. I have a dropdown comobox that is allways empty.

**Comment by kainoak** [comment]
Hi everybody,
i've a big problem with grafana, plug ImageIt, it doesn't work.
Who can send me a sample of json ? Thanks a lot.
(cause i think that the interface doesn't wor there are some errors like 'in' or 'lenght' ..., so perhaps json ll be ok)
thanks all.
