### ISSUE TITLE
Number format issue

### ISSUE THREAD

**Issue by stulincoln** [pierosavi/pierosavi-imageit-panel#11]
This is a great plugin and have found a lot of uses for it. One issue I have is that I can not drop the two decimal places when needed. Is there a way for format the number? I tried a cast in my query but it still shows '.00'

thanks

Stu

**Comment by pierosavi** [comment]
Hello, the only way to format it right now is directly on your query
I'll add it as a future feature but don't expect it soon
If you want to try implementing it feel free to make a pull request :)

**Comment by stulincoln** [comment]
Thanks. It seems wven if i dont pass it in my query it still shows the .00.
I will try a few other things.

Thanks for responding.

Stu

**Comment by ama9910** [comment]
Will you be publishing v0.1.2 on grafana.com so we can take advantage of Grafana unit format support?

**Comment by pierosavi** [comment]
It is now on pull request
