### ISSUE TITLE
Query Editor does not work with grafana v8.3.3

### ISSUE THREAD

**Issue by rvdwijngaard** [pierosavi/pierosavi-imageit-panel#116]
**Describe the bug**
This plugin does not work on hosted grafana (which is currently on v8.3.3). Rendering of the image works fine but as soon as you open the query editor the browser hangs. After digging in the code I found there is an infinite loop. 

The plugin works fine with grafana v8.2.x. 

**To Reproduce**

first with grafana v.8.2.2
```
docker run -it -p 3000:3000 -e GF_INSTALL_PLUGINSpierosavi-imageit-panel grafana/grafana:8.2.2
```
1. Create a new dashboard 
2. Select the imageit panel 
3. Add a sensor 

**Expected behavior**
A new sensor is created 

If you repeat these steps with grafana v8.3.3 you'll notice that the browser hangs as soon as you open the query editor and add one sensor or if you open the editor if there is already a sensor defined. 

**Grafana (please complete the following information):**
 - Browser firefox, chrome
 - Plugin Version 1.0.5
 - Grafana Version 8.3.3

**Additional context**
I think I know what causes this issue. I'll create a pull request which fixes this problem

**Comment by rvdwijngaard** [comment]
Hello @pierosavi is there any update on this? Is there anything I can do to help you to resolve this issue faster?

**Comment by TobiasI2001** [comment]
@rvdwijngaard 

Hello, is there a solution to this issue?

I ran into the same problem and I cant seem to get it solved.

**Comment by pierosavi** [comment]
@TobiasI2001 it's already fixed, update to latest version

**Comment by TobiasI2001** [comment]
@pierosavi  Thank you very much!
