### ISSUE TITLE
Slow response when add Sensors and Mappings.

### ISSUE THREAD

**Issue by YutaSuzu** [pierosavi/pierosavi-imageit-panel#118]
Dear pierosavi
Thank you for your great plugin for Grafana.
I'm starting to use Grafana v8.
But I have issue, would you consider it?

**Describe the bug**
Slow response when add Sensors and Mappings.
Entering one character causes the text box to lose focus.

**To Reproduce**
1. Go to 'Sensors'
2. Click on 'ADD'
3. Typing Name

**Expected behavior**
low response and hang up chrome. 
Entering one character causes the text box to lose focus.

**Grafana (please complete the following information):**
 - Browser [chrome 96.0.4664.110]
 - Plugin Version [1.0.5]
 - Grafana Version [v8.3.3 (30bb7a93c)]

Y Suzuki

**Comment by pierosavi** [comment]
Hi, this is already fixed in development and will be in v1.0.6 soon
