### ISSUE TITLE
Displaying NaN

### ISSUE THREAD

**Issue by MegaH01** [pierosavi/pierosavi-imageit-panel#12]
I have a simple influx query that returns a 6 digit integer.  
Created a new dashboard using the plugin but all I see for a value is "NaN"

Any ideas what is wrong?

![image](https://user-images.githubusercontent.com/51447897/59036350-16e50080-883d-11e9-90c8-289a9c54cb54.png)

**Comment by pierosavi** [comment]
You have to choose an unique name for the metric and write it in the ALIAS BY field and in the Sensor Name field
If this doesn't work try sending a screen of the Query Inspector output on the metric, hiding eventual private infos

**Comment by pierosavi** [comment]
@MegaH01 Is it fixed now?

**Comment by MegaH01** [comment]
Yes it's fixed.  Still like to be able to select a unit type like singlestat and have the value converted on the fly.  Not really useable now when I select an 100G interface and it displays 10+ digits long vs showing 90Gbps

That's how singlestat (and others) display the value when selecting the correct unit.

**Comment by pierosavi** [comment]
I'll add it on the feature request list, I'll take a look at how singlestat makes it work!
For now you can modify the query to divide the value returned as a workaround for this specific case

**Comment by LPnave** [comment]
@pierosavi  what do you mean by metric? as in like,using (Select * AS test)? and also the sensor name as test?

**Comment by pierosavi** [comment]
@LPnave 
Yes, like that

Also I did some tests with a MSSQL with all the reports that I want to divide based on the field "description" like they were different metrics 

`
SELECT
  $__time(ins_date),
  value as value,
  description as metric
FROM
  report_table
WHERE
  $__timeFilter(ins_date)
ORDER BY
  ins_date ASC
`

then, as sensor name if I put one of the descriptions (that are now metrics) it works.
I hope it helps

**Comment by LPnave** [comment]
@pierosavi  it worked Thanks!
