### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MegaH01** [pierosavi/pierosavi-imageit-panel#13]
Requesting the plugin support setting a Unit type (Data Rate, temperature, Percentage, etc) like others do.

**Comment by pierosavi** [comment]
You can already add it on the sensor tab on the Unit field

**Comment by pierosavi** [comment]
https://github.com/pierosavi/pierosavi-imageit-panel/issues/12#issuecomment-500841993

Closing this and adding it on features request
