### ISSUE TITLE
Background image/panel not adaptive

### ISSUE THREAD

**Issue by digithermo** [pierosavi/pierosavi-imageit-panel#14]
Hi,

I just realize that when I switch from my Mac screen to a big external screen and I am going to resize the Chrome windows, from big (ScreenShot_1) to small (ScreenShot_2), there is an issue with the resizing. I am not sure if it about the background picture (It seems to work to me) or about the panel.
The background picture it seems to adapt to the new size.

Viceversa, when I resize the Chrome window from big to small, part of the background picture goes cut off.

Hope I made myself clear.

-Marco.

![ScreenShot_1](https://user-images.githubusercontent.com/37805258/59597495-44ae2d00-90fa-11e9-8906-6648eab77728.png)
![ScreenShot_2](https://user-images.githubusercontent.com/37805258/59597505-4d9efe80-90fa-11e9-8d6f-5f3881e7890c.png)

**Comment by digithermo** [comment]
Here when I resize the window from small to big. The bottom part of the background picture is cut off.

![ScreenShot_3](https://user-images.githubusercontent.com/37805258/59597928-49271580-90fb-11e9-973f-10444803eae8.png)

**Comment by pierosavi** [comment]
@digithermo 
Since the last commit on master the image is always contained in the panel so it should have fixed your issue
It won't cut the image anymore but still create black bands around when the panel doesn't have the same aspect ratio, but now the image will be centered
Let me know if it's better now

**Comment by digithermo** [comment]
Ciao Piero,

Sorry, but the issue is not fixed.
You mentioned the case when you resize the window from big to small and you got the same as the image with the green arrow I posted above.
Have you tried vice-versa, to make the windows bigger? I still have the image cut.

Print screen Step_1a and Step_1a represent the windows small size. The image in the panel is perfect, even when I scroll down the page and I check the full dashboard.
Then I made the window bigger.
Print screen Step_2a and Step_2a represent the windows big size. Once I scrolled down to check the whole dashboard it's clear that the image has been cut. So I should resize the panel to get the whole image.

So if I send the dashboard to someone and he has to resize the window according to his monitor the dashboard could be incomplete.

Hope that it can help. I don't know how to make myself more clear. 

-Marco.

![Step_1a](https://user-images.githubusercontent.com/37805258/59855109-9366fb80-9374-11e9-9d73-03ae0d07da1e.png)

![Step_1b](https://user-images.githubusercontent.com/37805258/59855464-4b94a400-9375-11e9-8dbc-640435b4a668.png)

![Spep_2a](https://user-images.githubusercontent.com/37805258/59855145-aed20680-9374-11e9-8bd5-1521eb4066f8.png)

![Step_2b](https://user-images.githubusercontent.com/37805258/59855162-bb565f00-9374-11e9-8b4f-898f29033c66.png)

**Comment by pierosavi** [comment]
Can you confirm that you pulled the last master commit? 
It's commit https://github.com/pierosavi/pierosavi-imageit-panel/commit/7cc6a3bbba77f3b206f69e0452773c0746bb92a0 as of right now
You can't update it in the web interface, you have to manually git fetch and pull from your plugin directory
I'm asking because I see your version it's behaving like the old one :)

**Comment by digithermo** [comment]
@pierosavi 
I am not sure. I will check with our IT guys and I will keep you posted. 
Thanks for the quick reply.

-m.

**Comment by pierosavi** [comment]
No problem!
This is because for the "classic" plugin update I need to make a request to the Grafana team and it could take weeks to be approved. If you pull directly for master we can test it faster and I'll update it officially later on

**Comment by digithermo** [comment]
Hi @pierosavi 

My IT guy has updated the plugin. The new release has fixed the issue.
Thanks for the quick response!!!

-M.

**Comment by pierosavi** [comment]
Ottimo ;)
