### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by florianwgnr** [pierosavi/pierosavi-imageit-panel#18]
Some ideas that could improve working with imageit:

- ability to lock the sensors in place, so sensors cannot be moved by mistake. 
Because: end-user in kiosk-mode doesn't want to make changes. Also: after clicking on a sensor to follow a link and moving it a little bit, the dashboard asks to save changes.

- newest grafana version and Firefox: even with no link provided, every sensor is linked to grafanas main page. Please provide an ability to disable this link.

Thank you for your work!

**Comment by pierosavi** [comment]
Sadly grafana doesn't have a custom event to monitor when it enters kiosk mode or to check if you are admin/editor or user
That's why I still have to find a mode to lock the sensors effectively

> after clicking on a sensor to follow a link and moving it a little bit, the dashboard asks to save changes
> Please provide an ability to disable this link.

These two have been fixed today ;) you can update to the latest commit or wait next release!

**Comment by florianwgnr** [comment]
> Sadly grafana doesn't have a custom event to monitor when it enters kiosk mode or to check if you are admin/editor or user
> That's why I still have to find a mode to lock the sensors effectively
Okay, thank you for the explanation. Maybe you could implement a checkbox, that creators can check when they are finished. After that, the movement could be blocked...

> These two have been fixed today ;) you can update to the latest commit or wait next release!
Wow, good job - thanks!

**Comment by pierosavi** [comment]
> Maybe you could implement a checkbox, that creators can check when they are finished. After that, the movement could be blocked...

I just tried this with a lock icon on the top right corner
It keeps the state after a refresh 
Try updating to the last commit and let me know ;)

**Comment by florianwgnr** [comment]
> I just tried this with a lock icon on the top right corner
> It keeps the state after a refresh
> Try updating to the last commit and let me know ;)

Works great, thank you very much! 

But I have noticed something else: when displaying a sensor value, i.e. "9", the sensors are showing "9.00". Maybe you can implement a feature to set the number of decimal places?

Best regards

**Comment by pierosavi** [comment]
> Maybe you can implement a feature to set the number of decimal places?

This is now implemented in the last commit, together with true unit formatting and a metric list dropdown!
