### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by erickstorck** [pierosavi/pierosavi-imageit-panel#19]
Hi, I'm using your plugin to show sensors in a dashboard within a blueprint from our factory. It is working very well, you did a good job. 

We are wondering if it is possible to add an image to any sensor in the dashboard. Currently we can change the colors of sensors, but it would be great if we could add images also.

**Comment by pierosavi** [comment]
You can add a picture writing in the "display name" field this:
`_img-imageurl.jpg,height,width_`

You can try this in a sensor as reference:
`_img-https://upload.wikimedia.org/wikipedia/commons/c/c9/Moon.jpg,100,_`

If you don't set either eight or width the other is automatic

I see the feature is not written anywhere in the readme tbh, I'll add it later!

**Comment by erickstorck** [comment]
Good job, thank you!
