### ISSUE TITLE
Getting error on panel "value-color mapping"

### ISSUE THREAD

**Issue by JCP13** [pierosavi/pierosavi-imageit-panel#2]
Hi,

Thank you for updating this much needed plugin.  After I've installed it the "value-color mapping" panel does not display anything. When I looked at the console I see this error:
angular.js:14700 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('panel-editor-tab-bessler-pictureit-panelvalue-color mapping') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1554)

Any thoughts?

**Comment by TLMiot** [comment]
Hello,
I'm unable to replicate it, did you directly update it from the old version? Does your panel already have some data?

**Comment by JCP13** [comment]
Hi,

Thank you for your reply.  Yes, I directly update it from the old version. If that is the issue, what is the proper way to do a clean uninstall and re-install?

Thank you again.

**Comment by TLMiot** [comment]
The best way would be to delete the old version panels before upgrading, then recreating them. This is because some settings were modified or completely deleted from the old version. Please try to delete and recreate your panel

**Comment by JCP13** [comment]
Hi, sorry for taking so long to get back you. I did as requested but still getting the same error. I restarted and rebooted a number of times and same error. Is there something that maybe caching this and causing the conflict?

angular.js:14700 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('panel-editor-tab-bessler-pictureit-panelvalue-color mapping') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1554)
    at t.addDirective (https://<domain name>/public/build/app.469095018b321ef1da7c.js:1:94632)
    at t.link (https://<domain name>:3000/public/build/app.469095018b321ef1da7c.js:1:94842)
    at Object.link (https://<domain name>:3000/public/build/app.469095018b321ef1da7c.js:1:95087)
    at https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:7414
    at https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:55088
    at Ne (https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:55145)
    at ie (https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:50579)
    at https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:43466
    at https://<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:43483 "<panel-editor-tab editor-tab="tab" ctrl="ctrl" index="$index">"

Thank you in advance.

**Comment by JCP13** [comment]
Do you know which files you think has been deleted or overwritten? maybe I can manually update them. 
Better yet can you provide a copy of your working version?

Thanks.

**Comment by TLMiot** [comment]
All the files should be in *grafana-dir*/data/plugins/grafana-pictureit
Try reinstalling the old version, check if it works, if it does remove every pictureit panel, then delete the old one and install this version
Sadly I have no idea how to replicate your issue

**Comment by JCP13** [comment]
I am truly at a lost hear and I am not sure what is causing this.

I've deleted the old Pictureit from the plugin folder (/var/lib/grafana/plugins) and replaced it with your current version pierosavi-imageit-panel. To my amazement, the same issue.


angular.js:14700 DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('panel-editor-tab-pierosavi-imageit-panelvalue-color mapping') is not a valid name.
    at HTMLDocument.createElement (<anonymous>:1:1554)
    at t.addDirective (<domain name>/public/build/app.469095018b321ef1da7c.js:1:94632)
    at t.link (<domain name>/public/build/app.469095018b321ef1da7c.js:1:94842)
    at Object.link (<domain name>/public/build/app.469095018b321ef1da7c.js:1:95087)
    at <domain name>/public/build/vendor.469095018b321ef1da7c.js:130:7414
    at <domain name>/public/build/vendor.469095018b321ef1da7c.js:130:55088
    at Ne (<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:55145)
    at ie (<domain name>/public/build/vendor.469095018b321ef1da7c.js:130:50579)
    at <domain name>/public/build/vendor.469095018b321ef1da7c.js:130:43466
    at <domain name>/public/build/vendor.469095018b321ef1da7c.js:130:43483 "<panel-editor-tab editor-tab="tab" ctrl="ctrl" index="$index">"


I am running Grafana v5.4.3 (6539180)

**Comment by pierosavi** [comment]
The good news is that the bug is now fixed :)

The bad is that I'm not 100% sure why it happened and I don't know why it worked in grafana 6

I'll do a release called 0.0.2 for this and some performace improvements
I'm waiting for your feedback before closing this, just in case!

**Comment by JCP13** [comment]
I know, such a weird bug. It was driving me crazy. Ok, I will give it a try over the weekend. 

Thank you so much for looking into this.

**Comment by JCP13** [comment]
Hi pierosavi,

Yes, it's working now. Thank you for fixing this bug. Please continue doing a wonderful job, this is a much-needed plugin.

Cheers,  ;)
