### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by erickstorck** [pierosavi/pierosavi-imageit-panel#20]
Hi, Piero!
What about determinate exactly width and height of sensors?

I try it changing "width" and "panelWidth" in the panel json, but it does not work.

**Comment by pierosavi** [comment]
Hi,
the sensor is wrapped around the text, you can modify the text size in the "Size Coefficient" field
I don't see why you should modify the sensor size, what's your use case?

**Comment by erickstorck** [comment]
Yeah, I understand. But "Size Coefficient" modify all the sensors, I want to modify each sensor. Just for organization.

For example, I'm showing data from PH and pressure. But the size of each sensor is not the same, because the length is not the same too.  "7.1 PH" are smaller than "5.3 BAR"

I have a dashboard with ~60 sensors, and I need to show all of them in the same size.

**Comment by pierosavi** [comment]
I think I could add an individual size coefficient for every sensor and, if not set, it uses the global one
Could it work?

**Comment by erickstorck** [comment]
yeah, awesome.

**Comment by pierosavi** [comment]
Check the last commit https://github.com/pierosavi/pierosavi-imageit-panel/commit/7cf8ec7a4f8596d43ca6e550c2863573abe839c1 to try the new feature!

**Comment by erickstorck** [comment]
It's really a good job. Thank you!
