### ISSUE TITLE
URL Settings

### ISSUE THREAD

**Issue by ppnacho** [pierosavi/pierosavi-imageit-panel#21]
Hi,
I'm a beginner with this panel. I don't know who is the location of images and the url settings to read the images. I'm using Grafana in a docker container.

I hope that you help me.

Thanks,

**Comment by pierosavi** [comment]
The best practice is to setup a web server like apache or nginx that can deliver direct access to images in http, like this https://upload.wikimedia.org/wikipedia/en/9/95/Test_image.jpg

**Comment by ppnacho** [comment]
Hi,

Thanks, I've try whith one picture in a web server and works, but now I can't display the values of query, I don't know if I have to put something in link field (url). Is a link to sensor value?

Thanks,

**Comment by pierosavi** [comment]
You need to set a value in the ALIAS field in your query and set the same value in the Name field in you sensor
Also remember to check the "render value" box

**Comment by ppnacho** [comment]
I try your configuration but don't work. Shows "NaN" in the image.

**Comment by pierosavi** [comment]
Can you attach pics of the query and the sensor?

**Comment by ppnacho** [comment]
Hi, It works!!
Thanks
