### ISSUE TITLE
Query more than 26 letters (refId)

### ISSUE THREAD

**Issue by kelah** [pierosavi/pierosavi-imageit-panel#23]
Hi,
  Any workaround if we have more than 26 queries? 26 seems to be the limit and Grafana team have no intention to increase anytime soon :(.

**Comment by pierosavi** [comment]
Maybe wildcards would work as a workaround but if you have different metrics names it may be not possible

I found this: https://github.com/grafana/grafana/issues/4978#issuecomment-285300476 that could help, let me know

**Comment by kelah** [comment]
we decided to split to 2 or more panels (and images). solved our problem for now.
