### ISSUE TITLE
Postgres

### ISSUE THREAD

**Issue by CBZakaria** [pierosavi/pierosavi-imageit-panel#24]
How to work with postgres in ImageIt ?

**Comment by pierosavi** [comment]
You set up the metric that returns a value and give it an ALIAS
You add a Sensor and give it the same name as the metric ALIAS
This should work, you can send screenshots of what you tried and I can have a look at how to set it up :)

**Comment by CBZakaria** [comment]
I did it thank you ;)

**Comment by cesem589** [comment]
as you did CBZakaria, I am doing this query
SELECT time, count as production, location FROM historic_counter WHERE location='Production'

![image](https://user-images.githubusercontent.com/59579315/71987330-c1c30000-320c-11ea-83e6-2d12fb486df5.png)


I worked once but then the plugin breaks
