### ISSUE TITLE
Less than/Greater than operators

### ISSUE THREAD

**Issue by kelah** [pierosavi/pierosavi-imageit-panel#25]
Hi,
  In "Value Mapping" section, the ">"  operator is read as "Greater Than" and "<" read as "Less Than"? I am seeing the opposite behaviour.

Best regards.

**Comment by pierosavi** [comment]
Hello,
if you have a metric with value 20 and you setup the Value Color Mapping like

Operator: >
Compare To: 15

It will use the Value Color Mapping appearance settings because it checks if 20 > 15
Let me know if it isn't clear

**Comment by kelah** [comment]
Hi,
    I faced this 2 confusing scenarios:
Scenario on sensor 1:
metric value: 24.50
Operator: >
Compare To: 20
Evaluate as "True"

Scenario on sensor 2:
metric value: 26.80
Operator: >
Compare to: 3.99
Evaluate as "False"

This is all on the same panel. Is there any limit # sensor/panel?

**Comment by pierosavi** [comment]
That's weird
Can you check the type of value of sensor 2 metric? It could cause problems if the metric is a string

**Comment by kelah** [comment]
yes indeed! it was string. changed to float, works like a charm. thanks!
maybe can implement autodetect the value type?
