### ISSUE TITLE
Positioning sensor rectangle in the figure

### ISSUE THREAD

**Issue by s5uishida** [pierosavi/pierosavi-imageit-panel#26]
Thank you for your very useful plugin.

I have one question.

If I add a sensor, position it on the background figure, and release the mouse, the sensor rectangle will move slightly in the figure. This makes it difficult to place it exactly where I want it.

Is this something like that?
I am using v0.1.2.

P.S.

I have connected my following simple tool and ImageIt with Grafana. It is very useful.
Thank you for the ImageIt.

[https://github.com/s5uishida/rainy](https://github.com/s5uishida/rainy)
[https://github.com/s5uishida/rainy#create_dashboards](https://github.com/s5uishida/rainy#create_dashboards)

**Comment by pierosavi** [comment]
Hello, I pushed a new commit that fixes that weird "snapping" happening! 
Try it and if it fixes it for you I'll release a new update

Rainy seems very cool, good job!

**Comment by s5uishida** [comment]
Thank you for your quick response.

I confirmed that positioning can be performed accurately. It's very good!
I used PictureIt before, but I liked ImageIt very much.

Thank you very much again.
