### ISSUE TITLE
Option to hide the lock icon

### ISSUE THREAD

**Issue by Tormenta74** [pierosavi/pierosavi-imageit-panel#28]
While the lock button is a very useful feature, when using the panel in a small size, it's position is relatively inconvenient. I would propose adding an option that would allow to show / hide the icon in the panel editor. That way you can lock (or unlock) the sensors and leave them in that state without the ability to toggle the lock unless you edit the panel itself.

**Comment by pierosavi** [comment]
Hi, that seems like a really good idea! I'll have a look at it next week for sure :)

**Comment by pierosavi** [comment]
This is now on 0.1.2 pull request
