### ISSUE TITLE
zabbix map - imageit

### ISSUE THREAD

**Issue by kotviphp** [pierosavi/pierosavi-imageit-panel#29]
Hi

I add the URL https://zabbix-map... but on the panel, does not display pictures

![image](https://user-images.githubusercontent.com/25497579/67737409-420efd00-fa35-11e9-9a09-77e696bdbaf6.png)

**Comment by pierosavi** [comment]
The panel only works with pictures, make sure your link returns one.
I think your zabbix map is a representation of your network structure as a webpage, this is not supported.
