### ISSUE TITLE
"select a sensor metric" when metrics return no values

### ISSUE THREAD

**Issue by ADefossez-Zenika** [pierosavi/pierosavi-imageit-panel#32]
Hi there, 
I've played with this plugin last week : that was fun ^^

Anyway, my kafka topics are empty today, i used it to monitor kafka consumer lag (1 sensor by consumer) and so my metrics return no values. I have a message "please select a sensor metric".

Maybe can we return another message, instead  ? What's your thoughts ?

**Comment by pierosavi** [comment]
Hi,
Do you mean changing the message or the behavior in this case?

**Comment by ADefossez-Zenika** [comment]
HI, 
I mean the behaviour, because if we set a query (ie prometheus) : this query returns (or not) values : but if it don’t return any value, it can be OK, at the moment. (it will return something later as queries can be very specifics)
The plugin doesn’t handle a query that dont return values : maybe we can select query by their field-name (like A, B, C) and return something like "NC" if the query doesn’t return anything.

Am i Clear ?

**Comment by pierosavi** [comment]
I did some tests with prometheus for the first time.
The problem with that data source is that, for Grafana, when prometheus returns no value it's like the query doesn't exist at all
This is not true for other data sources like inlfuxdb or postgres
The only thing I could change in this case is the warning message to something like "NC" (as you suggested)

**Comment by ADefossez-Zenika** [comment]
Hi Piero, Thats exactly the point. We can display "NC" but be sure that the query stay "in memory" . I mean when this query will return data again, it must display it by default , without re-selecting it by editing the panel. I'm not sure it's the current behavior

**Comment by nctuevamax** [comment]
Hi Piero, I'm using InfluxDB as data source. I see same behavior as Zenika described.
I think "NC" or "Null" or "0" should be okay for me, something we could define by ourself should be even better.
Thank you for the wonderful plugin anyway, and looking forward to the next version regarding version compatibility issue^^

**Comment by mirkocomparetti-synesis** [comment]
I see the same behavior with influxdb as @nctuevamax reported.
Maybe doing something like in the singlestat panel where the query returns a "null" variable that we can then map with value mapping to the specific message that we need.
Thanks

**Comment by Ben0it** [comment]
Hi, since I upgraded to Grafana 7.x, the sensor lists are empty **(1)** in every instances of ImageIt. An additional warning **(2)** shows "InfluxDB Error: not executed" 'see image below).

I have updated the ImageIt with the latest code available in Github, same behavior. Did I miss something ?

Best regards,

Benoît.

![image](https://user-images.githubusercontent.com/25719453/85663364-48837080-b6b9-11ea-8fad-7a168dc202f4.png)

**Comment by heliodor** [comment]
The fact that no metric is listed in your red #2 arrow makes me think that no data is being returned by your query for the 1h time window you chose. Take that query and put it in a new graph panel to make sure it _does_ return data.

**Comment by Ben0it** [comment]
@heliodor : you were right, one of my queries was bugged (don't know why, it worked before).

So I disabled all queries and enabled them one by one : I could track the culprit. 

Now I get the proper value display, thanks for the hint !

**Comment by Ben0it** [comment]
After I upgraded to Grafana 7.0.4 this morning, ImageIt shows no more value.

When trying to edit the panel, I get this error : 

![image](https://user-images.githubusercontent.com/25719453/85848816-1b62bb00-b7aa-11ea-9209-1eb08426a8e2.png)

Am I the only one affected ?
