### ISSUE TITLE
ImageIt Panel not showing edit top-bar.. :(

### ISSUE THREAD

**Issue by lenny1972** [pierosavi/pierosavi-imageit-panel#33]
I'm havi ng issues using this panel in my Grafana docker installation.
I'm currently running a dockerized Grafana (Grafana v5.4.3 (6539180))  and after installing the latest ImageIt plugin from inside the docker exec wi the command _grafana-cli plugins install pierosavi-imageit-panel_ and restart the grafana docker I see the ImageIt panel withiin the "Add Panel" menù of Grafana but after selecting the "ImageIt" plugin i see on the dashboard just a blank panel (I only see the Panel "resize" angle on the right lower part of the Panel but I don't see the Panel "Edit" top bar). Attached the screen that I see after adding the ImageIt panel to my Dashboard.

It's a kknown issue? If so is there a solution for that?
Thanks in advanced
Leonardo

![ImageIt Panel Issue](https://user-images.githubusercontent.com/13016843/69755515-acac7900-1158-11ea-836c-cb8a009db6b6.png)

**Comment by ADefossez-Zenika** [comment]
Hi Lenny, I had the same issue, and had to upgrade my grafana instance to 6.XX

**Comment by lenny1972** [comment]
Thanks for you reply Aymeric.

Leonardo

Inviato dal mio OnePlus 3T

Il gio 28 nov 2019, 10:46 Aymeric Defossez <notifications@github.com> ha
scritto:

**Comment by pierosavi** [comment]
Ciao Leonardo,
I didn't know about this issue, please upgrade to v6 if you can as Aymeric said
Let me know if you can't and I'll look into it, still v5 support is not one of my main focus right now

**Comment by lenny1972** [comment]
Ciao Piero, mi sembra di capire che sei anche tu del Bel Paese...

Dalla descrizione del plugin mi sembra di capire che è proprio quello che
serve a me..Ho estrema difficoltà nel fare un upgrade alla v.6 anche perchè
sto già in produzione e non vorrei avere impatti sugli utenti...

Attualmente per quanto problema sono costretto ad utilizzare il plugin
"epict Panel" che però non ha tutte le features Di quello che hai
sviluppato tu... :(

Ti sarei veramente grato nel caso in cui riuscissi a rilasciare un fix
anche per la versione che ho installato  (5.4.3).

Grazie in anticipo e se hai bisogno di altre informazioni per identificare
il problema e sviluppare un eventuale update (per risolvere tale problema)
sono completamente a tua disposizione.

Ciao Leonardo

Inviato dal mio OnePlus 3T

Il gio 28 nov 2019, 11:48 Piero <notifications@github.com> ha scritto:

**Comment by pierosavi** [comment]
Hi, I prefer to keep this in English so other people can understand :) 
The compatibility issue is now fixed in https://github.com/pierosavi/pierosavi-imageit-panel/commit/52567c511fb74542dd196f7b6a96fd24cd94aa70 , I will release a new version officially soon

**Comment by lenny1972** [comment]
Thanks a lot Piero!!

I'll wait for the new plugin version.

Regards,

Leonardo

Inviato dal mio OnePlus 3T

Il lun 9 dic 2019, 10:01 Piero <notifications@github.com> ha scritto:

**Comment by pierosavi** [comment]
Hi, the new version is now available, reopen the issue if you encounter the problem again

**Comment by lenny1972** [comment]
Thanks a lot Piero I'll check it and let you know.
