### ISSUE TITLE
In Grafana version 6.5.1 my sensors are not displayed

### ISSUE THREAD

**Issue by JonasMock** [pierosavi/pierosavi-imageit-panel#34]
After downgrading Grafana back to version 6.4.4 my sensors where displayed as expected.

**Comment by GustavoLayrisse** [comment]
it looks like plugin is compatible until grafana version 6.4.5.

**Comment by pierosavi** [comment]
The compatibility issue is now fixed in 52567c5 , I will release a new version soon

**Comment by raidsec** [comment]
i could confirm that i have the same problems. My plugin is working until 6.4.5. After that version I got some strange issues. See here:

![image](https://user-images.githubusercontent.com/33294982/71519822-50548a80-28b9-11ea-8a3f-de06adee5af5.png)

![image](https://user-images.githubusercontent.com/33294982/71519826-55193e80-28b9-11ea-8b4e-ddb735fd61e7.png)

When will the new version be released?

**Comment by pierosavi** [comment]
The update is now in PR here https://github.com/grafana/grafana-plugin-repository/pull/544

**Comment by megardt** [comment]
I'm seeing the same thing here;
![image](https://user-images.githubusercontent.com/1398181/72239747-4a151c80-35e2-11ea-85bd-c640a975a7dc.png)


![image](https://user-images.githubusercontent.com/1398181/72239765-6022dd00-35e2-11ea-9940-8d3a4943c93c.png)

Thanks for a nice plugin by the way :)

**Comment by raidsec** [comment]
When will the new version be released?

**Comment by pierosavi** [comment]
@raidsec the pr is still open, I would say 1 week max

**Comment by raidsec** [comment]
Ok, good to know. Thank you for fixing.

**Comment by suvajit** [comment]
Stuck with this issue on Grafana 6.5.0 update. Is this fix available in 0.1.3 release ?

**Comment by pierosavi** [comment]
The update Just got accepted, I'll close the issue in a few days

**Comment by suvajit** [comment]
Sorry, where can i get this fix ? I am not finding a release or branch for this fix ?
