### ISSUE TITLE
Images url: images hosted on same server

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [pierosavi/pierosavi-imageit-panel#37]
Hello,
I have a machine that is running grafana with your useful plugin. I have an apache instance on the same server: how can I access an image exposed on that server? I can configure an url using the IP, but I'd like to use some variables or something like "localhost".

Thanks,
Mirko

**Comment by pierosavi** [comment]
Hi Mirko,
You can't set the urls as localhost because they are loaded from the client, not served from a backend.
I think the best way would be giving an hostname to the server and limit it to your network if the images can't be public

**Comment by mirkocomparetti-synesis** [comment]
How can I make it public. I see examples with "/public/..." is the only way to use a URL, or can it be the uri of an image placed in a specific folder of the server that is hosting grafana?
I cannot understand how can I use it.

Thanks

**Comment by pierosavi** [comment]
I can't help with that, I don't know your specific case but I suggest hosting your images somewhere else or with a web server. Setting localhost directly is not supported
