### ISSUE TITLE
Problem with dragging

### ISSUE THREAD

**Issue by smargo171** [pierosavi/pierosavi-imageit-panel#38]
Hello, thanks for the great plugin. However I am not able to drag the sensors.
When I define a new sensor, I can drag it, but can not stop dragging. 

If I leave the panel, some position of the sensor is saved, but I can't change it. The cursors changes to the hand , but it does not picking up the sensor to drag. 

Or am I missing something obviuos?

Thanks!

I am using latest Grafana and latest plugin, on Windows 10.

**Comment by pierosavi** [comment]
Hello, what browser are you using?
