### ISSUE TITLE
Value Mapping bug and feature that relates to the bug

### ISSUE THREAD

**Issue by JCP13** [pierosavi/pierosavi-imageit-panel#4]
Hi TLMiot,

I have another issue, the good news it's a different one.

In the "Sensor" tab, I have set a background field to be transparent. On the "Color Mapping" tab, I have provided the Color Mapping Name and set it to red. In "Value Mapping Tab", I set the value to "=>80". When the value is 80 or over, the background sets to red. The issue is that if the value goes back to below 80 the background color never resets.
If I go back to the "Sensor Tab" that field background is set too red and not transparent. The background color is not resetting back to its original settings.

As for the related feature, is it possible to be able to select "Font Color" or "Background"?
for my purpose, I only want the "Font Color" to change.

Thank you again,

Cheers.

**Comment by pierosavi** [comment]
> The background color is not resetting back to its original settings

Fixed in 3b4b18d4cc43020261ce54a34d5349fce62fe040

> As for the related feature, is it possible to be able to select "Font Color" or "Background"?
for my purpose, I only want the "Font Color" to change.

I'll look on this later today or tomorrow

Overall the mapping feature needs a core rework as the original one had some serious problems, so if you have other qol improvements/features this is the best time to share :)

**Comment by JCP13** [comment]
Thank you pierosavi.

Since you asked, here is my list:

1)  "Value Mapping Tab": Select "Font Color" or "Background"  or both but able to set the color individually 

2) "Value Mapping Tab": Set the "Font Color" or "Background" or both to blink

3) "Sensor Tab": Set font to bold

4) Better snap to grid or not use it at all. Just drag and drop the item and it stays where it is. No auto adjusting but it can be a setting you turn off or on).

5) This is a long shot: If in your "Metrics Tab" you have a query that has multiple output values, let's say length, width, height, and depth.  It would be cool to display all of them vertically or horizontally. For horizontal, if we want a wrap around let's say on the third value, we can a text field and use a Pipe or something.
Horizontal wrap on third value Example:
"v1, v2, |v3, v4" or "v1 v2 |v3 v4"
result:
67 180 
50 20

Horizontal wrap on second value Example:
"v1, |v2, v3, v4" or "v1 |v2 v3 v4"
result:
67 
180 50 20

Horizontal wrap on second and fourth value Example:
"v1, |v2, v3, |v4" or "v1 |v2 v3 |v4"
result:
67 
180 50 
20

Horizontal wrap on second and fourth value, as well as Units Example:
"v1L, |v2W, v3H, |v4D" or "v1L |v2W v3H |v4D"
result:
67L 
180W 50H 
20D

I hope this makes sense. This would help to avoid having to create three separate queries and giving each one an "Alias By".
Yes, it will be controlled as a block by the Senor, Color Mapping and Value mapping Tab; and that's ok.

Thank you again, guys! :)

**Comment by pierosavi** [comment]
Thank for the feedback

1, 2, and 3 will be definitely be done in the next few days

The snapping on 4 is due to the browser decimal precision in the percentage offset of the sensor, it's like that so the browser doesn't have to recalculate the position in pixels every time, I'll try to find a better way in the future

5 is cool but it'll take a bit of time obviously

To be clear I'm still @TLMiot but I'll continue the development on this account :)

**Comment by JCP13** [comment]
That is awesome!! I knew items 4 and 5 would be a major rework. 

Thank you :)

**Comment by JCP13** [comment]
Hi TLMiot,

I have one more feature request.

6. "Sensor Tab": To be able to adjust the height and width of the objects on the "Sensor Tab" as well as on the image/canvas.

Thanks.

**Comment by pierosavi** [comment]
@JCP13 Check out https://github.com/pierosavi/pierosavi-imageit-panel/commit/448b0ef971efe31ea59f901c783db706c0b00141

It will broke things for existing value color mappings, don't update it directly in production

**Comment by JCP13** [comment]
@TLMiot

That's ok for me because I have not setup color mapping yet.

**Comment by xkilian** [comment]
5. Is an interesting idea. Please also consider the following implications:

- You may not want to always display all or any values at all but simply show a state (colour and description text)
- You may want to hide values not currently crossing a threshold (like status panel plugin)
- This has to be compatible with value mapping(text and emoji/font awesome) and thresholds

I admit I like very much the way Status panel handles multiple values. It is very elegant. Though it can only show them in a vertical fashion. Having multiple layout options is interesting.

**Comment by JCP13** [comment]
@TLMiot, thank you again for your hard work. I will test your updates by the end of the week.

@xkilian, Good catch. Yes, I did think about these implications but thought it would be better to keep it simple for now. The coding can get complex and more thought would have to go into it. The Status Panel,  I will look into. Nice feedback!

**Comment by JCP13** [comment]
@TLMiot, I just started testing the fix for the "Color Mapping" tab and now color is not changing at all. I set the threshold value well below, still no color change.
example: 
if "Value Color Mappings" =>40 (change to red)
The output value is 70 and no color change.

**Comment by pierosavi** [comment]
Note that you have to set the color mapping on the new select on the sensor tab (on top)

![image](https://user-images.githubusercontent.com/15440183/55935761-ba96a380-5c34-11e9-832f-513d66aac444.png)

**Comment by JCP13** [comment]
Strange, I am not seeing the new fields in the "Value Mapping Tab". Are the new updates on the master or the Dev branch?

**Comment by JCP13** [comment]
It looks like it's on the dev branch. I'll jump on this once I get a little downtime.

**Comment by pierosavi** [comment]
It was on dev but I merged on master after my last comment :)

**Comment by JCP13** [comment]
ok, I updated Grafana to the latest and grabbed the lastest bits. The only issue that I see now is the "Value Mappings" it only giving me a checkbox.


![image](https://user-images.githubusercontent.com/1745045/55997525-a91ebd00-5c6f-11e9-94ca-cee041756329.png)

**Comment by pierosavi** [comment]
It's empty because you have to add a value mapping below the sensor tab, before assigning to a sensor

**Comment by JCP13** [comment]
Ok, got and it looks good by the way.

Some issues that I found so far.
1) On the "Settings" tab you're no longer able to set Background Color as transparent using the UI 

2) If you already have set the Background Color that is transparent before the update it works well but when setting it to blink value you see the borderline.

3) In general, I find the Color picker after you click to display it, it displays the Color Pick UI intermittingly. It intermittingly displays and disappears after a second or so. 

1) On the "Value Mapping" Tab. When you try to select the Background Color (on an item before the update), the color picker works intermittently. on the Chrome debug console I get this error. 
react-dom.production.min.js:198 TypeError: Cannot read property 'indexOf' of undefined
    at g (namedColorsPalette.ts:164)
    at me (Switch.tsx:48)
    at Ji (react-dom.production.min.js:150)
    at Fo (react-dom.production.min.js:178)
    at Va (react-dom.production.min.js:232)
    at qa (react-dom.production.min.js:233)
    at Ls (react-dom.production.min.js:249)
    at As (react-dom.production.min.js:248)
    at Ps (react-dom.production.min.js:251)
    at Cn (react-dom.production.min.js:85)
fa @ react-dom.production.min.js:198
n.callback @ react-dom.production.min.js:210
ia @ react-dom.production.min.js:193
ra @ react-dom.production.min.js:193
Ha @ react-dom.production.min.js:217
Wa @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Os @ react-dom.production.min.js:250
Ls @ react-dom.production.min.js:249
As @ react-dom.production.min.js:248
Ps @ react-dom.production.min.js:251
Cn @ react-dom.production.min.js:85
react-dom.production.min.js:248 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at g (namedColorsPalette.ts:164)
    at me (Switch.tsx:48)
    at Ji (react-dom.production.min.js:150)
    at Fo (react-dom.production.min.js:178)
    at Va (react-dom.production.min.js:232)
    at qa (react-dom.production.min.js:233)
    at Ls (react-dom.production.min.js:249)
    at As (react-dom.production.min.js:248)
    at Ps (react-dom.production.min.js:251)
    at Cn (react-dom.production.min.js:85)
g @ namedColorsPalette.ts:164
me @ Switch.tsx:48
Ji @ react-dom.production.min.js:150
Fo @ react-dom.production.min.js:178
Va @ react-dom.production.min.js:232
qa @ react-dom.production.min.js:233
Ls @ react-dom.production.min.js:249
As @ react-dom.production.min.js:248
Ps @ react-dom.production.min.js:251
Cn @ react-dom.production.min.js:85

I'll do more testing later this weekend.

**Comment by JCP13** [comment]
@TLMiot, I was able to work around the issues. Once I figured out the patterns that worked, I was able to move forward. Now, I have everything set up the way I want, and so far everything is working as expected.

A big kudos to you for taking over this plugin project and propelling it to the next level !!! 🥇 👍

**Comment by pierosavi** [comment]
That's great! How did you fix n.4?

I'll close this issue next and add the features request on the main list

Also tag me at this account an not TLMiot from now on to create less confusion :)

**Comment by JCP13** [comment]
@pierosavi  got it, LOL. 

I didn't fix it per se, just worked around it and it's too strange and convoluted to write out. I don't know if it's just me or other people are having the same issues. 
So, not that I don't want to explain, it's just something that I would have to show you. Please let me know if that's something you'll like to do.
