### ISSUE TITLE
Feature request: value mapping, value to string

### ISSUE THREAD

**Issue by wz2b** [pierosavi/pierosavi-imageit-panel#42]
I would like to make a feature request, to add "Value Mappings" similar to what the built-in "stats" page does.  Consider the attached example: my rainwater tank is full, because it's disabled.  You can tell because the make-up water valve is open.  But it says "1" which is not very friendly.  I'd like some kind of value mapping that lets me say 1/0 is "on"/"off" or "open"/"closed" or "occupied"/"vacant" as the case may require.

![image](https://user-images.githubusercontent.com/1521209/76655600-08eaab80-6544-11ea-8970-ccd4459e5942.png)

**Comment by pierosavi** [comment]
Hi Christopher, this will definitely be a future for next release, I'll keep you updated

**Comment by heliodor** [comment]
Along those lines, it would be nice if this plugin would be able to render data from queries that return string values instead of numerical values. I'm trying to show the values "ON" and "OFF", where those values come directly from the database without any mapping.

**Comment by pierosavi** [comment]
@heliodor that should already be the case, is it not working for you?

**Comment by heliodor** [comment]
@pierosavi It's not the the case by default. It's showing NaN. I figured it's trying to cast it to a number, so I deleted the number from the decimals box, and still not working. This time around, I found the Misc > System Locale unit type, and that worked!

I would think that unit: misc > none should render the value as-is without caring for its type, the presence of a value for "number of decimals" would pass the value through a formatter (leading to NaN for non-numerics), and choosing a different unit type would take precedence (as it does now).

Back to the original point of this github issue, one more reason for implementing value mappings is to make it easy to translate text into the language of the dashboard user, so that a value of "ON" in the database can be rendered in another language.

**Comment by pierosavi** [comment]
Thanks for writing your steps, it helps a lot! The unit type algo is mantained by grafana so I'm not currently 100% sure how it parses, but I can add exceptions for strings, it seems a good idea now.

Also I was thinking of adding an "override text" option to add to the existing value mapping feature

**Comment by smurfz** [comment]
I came here for the same feature request, and the NaN problem. I'm running Grafana 6.7.3, and for me it was _misc > locale format_. Thanks @helidor for the workaround.

**Comment by cyanghsieh** [comment]
Not sure how's the progress of this feature. 
This feature is also important for my application. I fail to store mapping data into database since influxdb doesn't allow me to put Chinese/Japanese character into it. Therefore I am looking forward to having this value to string feature and thanks @heliodor for all the effort you spend.

**Comment by thomasmatt88** [comment]
I'm working with Grafana v5.2.4. and I don't see  _Misc > System Locale_ or _misc > locale_ as unit types. Is there another workaround to handling string values?

**Comment by heliodor** [comment]
@thomasmatt88, I can't answer your question in particular but I'd recommend upgrading your Grafana to v6.x if you can. Grafana has always gone to great lengths to ensure backwards compatibility. The v7 GUI layout has changed quite significantly but going from v5 to v6 should be pretty straightforward.

**Comment by thomasmatt88** [comment]
Thanks @heliodor. Unfortunately, I don't have access to the server it is hosted on so I can't upgrade. However, I realized in my version that I needed to choose _none -> locale format_ which worked!

**Comment by GilesLesser** [comment]
Any update on the original feature request?
I'd love to use value mappings to display cardinal direction text (eg "N","NE","E","SE", etc) in place of directions in degrees. This is possible in other Grafana visualisation types by setting up (multiple) mappings of value ranges to text strings. I assume that if the OP's request was fullfilled that would satisfy my need too.

For example, there would be multiple mappings along the lines of this (copy/pasted from another panel type)
```
    "mappings": [
              {
                "from": "11.25",
                "id": 1,
                "operator": "",
                "text": "NNE",
                "to": "33.75",
                "type": 2
              },
              {
                "from": "33.75",
                "id": 2,
                "operator": "",
                "text": "NE",
                "to": "56.25",
                "type": 2
              },.... etc
```


Many thanks. Plugin much appreciated as is, but this would really help.

**Comment by vernazza** [comment]
Hi, I'm having the same problem with Grafana 7.x and plugin 1.0.3
My data is returned as a string (on/off), but I always get NaN, even if I select "Locale format".
Right now I'm using the valueBinary instead of value, that's returning an int (1/0), but showing the text would be great

**Comment by ChristopherChan123** [comment]
hey @pierosavi is there a reason why you added the line:

value = fieldDisplay.display.numeric;

on Line 93 in src/ImageItPanel.tsx?

I think this may be the reason why we cannot display string values in the current version of ImageIt. Let me know what you think. 

Thanks!

**Comment by pierosavi** [comment]
This feature is in v1.0.5, currently in review

**Comment by ChristopherChan123** [comment]
> This feature is in v1.0.5, currently in review

Looking forward to it. Thank you very much!

**Comment by pierosavi** [comment]
1.0.5 is out, I'm closing this :)
