### ISSUE TITLE
picture url with password+username

### ISSUE THREAD

**Issue by na-am** [pierosavi/pierosavi-imageit-panel#44]
setting the url to 
   http://username:password@mycam.mydom.com/snap.jpg
isn't working. in my browser of course it is
how can i access a picture with username/password?

thx

**Comment by pierosavi** [comment]
Hi, is this still not working?
It's an html img tag so it should work normally, that's weird
If you still can't load it can you check the browser console for errors?

**Comment by heliodor** [comment]
Chrome may be to blame. It's partially blocking such urls and at some future version will block all of them:
https://medium.com/@lmakarov/say-goodbye-to-urls-with-embedded-credentials-b051f6c7b6a3

Check the dev console for a message related to this, if you're using Chrome.

**Comment by smurfz** [comment]
I am using Chrome. The way I worked around this is to open the image URL on another browser tab. Chrome will ask to authenticate (user/pass popup). Once authenticated, the browser will assume authenticated, and the panel will be able to load the image. Of course, when you close the browser, you have to repeat. It's not ideal, but I generally have grafana open for  a long duration, so it's a small cost.
