### ISSUE TITLE
Dashboard continuously prompt for save changes

### ISSUE THREAD

**Issue by Alcarin** [pierosavi/pierosavi-imageit-panel#46]
As mentioned also in [this ](https://github.com/grafana/grafana/issues/20610) issue, "uncache" value is changing continuosly and force the dashboard to a request to "save changes" everytime you try to exit form the dashboard. Issue seems happen every time auto-refresh is active and refresh the dashboard.

![save](https://user-images.githubusercontent.com/5025925/78566740-f6505300-781f-11ea-990a-8c12df3abe1b.PNG)

![diff 2](https://user-images.githubusercontent.com/5025925/78566103-0d427580-781f-11ea-9601-33b8d0f877cb.PNG)

![diff 1](https://user-images.githubusercontent.com/5025925/78566108-0ddb0c00-781f-11ea-8b90-f697cbbec64a.PNG)

**Comment by pierosavi** [comment]
Fixed in 1.0.0
