### ISSUE TITLE
Plugin not in plugin list @grafana webinterface

### ISSUE THREAD

**Issue by BRNMCP1337** [pierosavi/pierosavi-imageit-panel#48]
Hi, 

the imageit-panel is installed but is not displayed in the grafana plugin list @ web interface
furthermore, the panel including the imageit-panel throws an error:

![Bildschirmfoto 2020-04-17 um 11 18 37](https://user-images.githubusercontent.com/63773746/79553720-3247ab80-809d-11ea-8c28-d194fd889d62.png)

**Grafana-cli plugins ls:**
```
> grafana-cli plugins ls
installed plugins:
agenty-flowcharting-panel @ 0.7.0
bessler-pictureit-panel @ 1.0.0
briangann-gauge-panel @ 0.0.6
grafana-clock-panel @ 1.0.3
grafana-image-renderer @ 1.0.12
grafana-piechart-panel @ 1.4.0
grafana-worldmap-panel @ 0.2.1
jdbranham-diagram-panel @ 1.6.1
larona-epict-panel @ 1.2.2
michaeldmoore-multistat-panel @ 1.2.7
mtanda-histogram-panel @ 0.1.6
pierosavi-imageit-panel @ 0.1.3
ryantxu-ajax-panel @ 0.0.7-dev
savantly-heatmap-panel @ 0.2.0
scadavis-synoptic-panel @ 1.0.4
```
 please help, because unfortunately I can't use this plugin now.

**Comment by pierosavi** [comment]
@BRNMCP1337 can you try updating and retrying?
