### ISSUE TITLE
Want to know Ideal Size of the pic which can be uploaded here

### ISSUE THREAD

**Issue by anshul27jain** [pierosavi/pierosavi-imageit-panel#49]
I have a image of Resolution **1944 * 1668**. It is not loading properly.
**Could you please suggest any way by which huge files can be loaded via this Plugin?**

**Comment by smurfz** [comment]
While I don't have an answer to your question, I keep my image size to be no bigger than what I can show on the screen.

**Comment by pierosavi** [comment]
@anshul27jain What do you mean by it's not loading properly?

**Comment by anshul27jain** [comment]
Issue solved by increasing quality of file.
Now i want to know another thing. 

Please explain how **_Size Coefficient_** can be in use?

**Comment by heliodor** [comment]
> Please explain how **_Size Coefficient_** can be in use?

@anshul27jain, if you need help using this plugin, StackOverflow is a more appropriate place to ask. Github Issues is for reporting and discussing issues and bugs.
