### ISSUE TITLE
Metric isn't shown on map

### ISSUE THREAD

**Issue by sharkyzz** [pierosavi/pierosavi-imageit-panel#5]
Hi Guys,

Great work! I really like to make use of this panel, because it would be very useful to monitor temperatures etc. in our datacenters. Unfortunately the metrics are not shown on the map itself. Am I doing something wrong ?

Here I defined the query to one of our temperature measurements in Influx

![Screenshot 2019-04-11 at 13 42 13](https://user-images.githubusercontent.com/1429655/55955120-cbf5a500-5c60-11e9-9d9a-b36765d0a4e2.png)

And here I added the sensor. I suppose it works by referring to the alias of the query ?

![Screenshot 2019-04-11 at 13 42 38](https://user-images.githubusercontent.com/1429655/55955211-1e36c600-5c61-11e9-9573-a455674da395.png)

Thanks in advance for your help!

**Comment by sharkyzz** [comment]
Btw, i'm using the latest grafana (6.1.3)

**Comment by pierosavi** [comment]
>  I suppose it works by referring to the alias of the query ?

That's correct :)
You need to check the "Render value" checkbox, everything else seems right

**Comment by sharkyzz** [comment]
Oh haha, that simple. Thanks a lot! It works now. Going to test with it further now :)
