### ISSUE TITLE
Local file for image URL

### ISSUE THREAD

**Issue by Fleroux83** [pierosavi/pierosavi-imageit-panel#50]
Hi, 
Thanks for your great plugin.
I'd like to use a local file for the image URL.
I write file:///home/user/example.jpg for the image URL but it does not work.
The plugin works fine with an URL in a web site.
What is the syntax for a local image?

I use Firefox for CentOS Linux 1.0.

Thank

Fabrice

**Comment by Fleroux83** [comment]
Hi,
Nobody to answer me?

Thank

Fabrice

**Comment by heliodor** [comment]
@Fleroux83, this is caused by the way browsers work. It doesn't have anything to do with this plugin. See https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local

**Comment by Fleroux83** [comment]
Thank for your help. I've no error in the browser's inspector windows. I can see a file in my brower with ///home/user/example.jpg.

**Comment by Fleroux83** [comment]
I've tried with Opera Browser and I've the same problem.

**Comment by tses89214** [comment]
@Fleroux83 
maybe you can use some website you can upload pictures there (e.g. Imgur) to get a url of your pictures.

**Comment by Fleroux83** [comment]
my hosts have no access to Internet...

**Comment by pbaumard** [comment]
One way to support this use case would be to support [Data URIs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) in the plugin, e.g. `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==`

**Comment by xkilian** [comment]
The better way imo would be to permit the plugin to manage dropping image files to the grafana server or the same thing on the different web server. Ideally a managed interface for dropping images to a web server that can be read by Grafana Plugins. The interface should be authenticated, logged, etc. (already done in grafana). something like dropjone.js or other manager

**Comment by pierosavi** [comment]
@Fleroux83 I put some informations on that on the repository readme
