### ISSUE TITLE
Plugin is broken since Grafana 7.0.4

### ISSUE THREAD

**Issue by frdve** [pierosavi/pierosavi-imageit-panel#54]
Since the update to Grafana 7.0.4, the plugin stays black in the dashboard and does not show image and values.  When opening Edit, it crashes and show the error below:
![afbeelding](https://user-images.githubusercontent.com/66672043/85867779-a69f7900-b7c9-11ea-81f1-563e1bc7ce39.png)
Checking the image location manually shows that the image still works (image: https://www.globalspec.com/ImageRepository/LearnMore/20123/Refrigeration-Cycle1ff69be7991834f07807f6d2c2dc95e18.gif).

**Comment by Ben0it** [comment]
+1

Got the same problem [since yesterday](https://github.com/pierosavi/pierosavi-imageit-panel/issues/32#issuecomment-650112877).

**Comment by frdve** [comment]
Any updates on the issue? 
Thanks in advance!

**Comment by HenrikRolandHansen** [comment]
Same issue getting this error when trying to edit

An unexpected error happened
Detaljer
TypeError: Cannot read property 'offsetWidth' of null

**Comment by anaconics** [comment]
Hit this today. Anyone looking into this??

**Comment by frdve** [comment]
Not that I'm aware of.. :( Too bad, because it is the best Image plugin in Grafana...
I see an 0.1.4 update in the pipeline, but I'm not sure if this will be fixed: https://github.com/pierosavi/pierosavi-imageit-panel/pull/53

**Comment by pierosavi** [comment]
@frdve I'm looking into this, I'll keep you updated

**Comment by frdve** [comment]
Thank you! 😃

**Comment by anaconics** [comment]
Thank you

**Comment by pierosavi** [comment]
Hi all, sadly ImageIt v0.x.x compatibility with Grafana 7.0.2+ **will not** be a thing.

As some of you probably know the Grafana team is slowly deprecating the old mode of building plugins (Angular v1), so it was a matter of time until something broke beyond repair in ImageIt.

So, for now, If you can, revert your grafana installation to 7.0.0 if you really need the plugin.

But don't worry, ImageIt v1.0 is coming!

I've been working on migrating the plugin to the new method (React + TypeScript) for a while now, it's not ready yet but it's getting there.

With the new version it'll be way easier to add new features and fix bugs for the devs and it'll look and perform better for the user.

By default this would mean losing all ImageIt v0.x.x data during the update but I will make sure to build a tool to make the update as smooth as possible and keep all the data.

I'll keep all the issues open, including this one, and close the old ones when v1 is release.

If any React dev is interested in contributing please let me know

**Comment by aspro-at** [comment]
Thank you! 👍

**Comment by dvdl16** [comment]
Thank you! Can't wait, best of luck with the development of v1

**Comment by befantasy** [comment]
this plug-in is very useful!

**Comment by pierosavi** [comment]
Hi all, I'm very close to releasing version 1
The only big thing missing is the value-mappings feature that I decided to rename to Overrides
That allows you to override some properties of the sensor like value color, background color, blink.. when some conditions are met (think about a temperature sensor blinking and becoming red when the temperature is above 40°)
With the grafana changes in the new sdk it's not as easy as before and I need to think about a stable workaround to make them work

If you don't need that feature and can/know how to play around with your Grafana instance you can already clone the repo on `react-migration` branch and `yarn build` the plugin in your grafana 7+ instance
Keep in mind that's still the dev build until it's fully released on the grafana "store", but let me know if you find any issue

🚀

**Comment by minida28** [comment]
Hi @pierosavi , thank you for your great work !
I've tested the react version on Grafana 7.2.1 and it works fine.

I found some issues though:
1. List of metric names does not show up automatically. Previous version does.
2. Font size is not responsive.

Pictures below show the comparison of font responsiveness beetween the previous version of the plugin and the new react version.

![image](https://user-images.githubusercontent.com/3026584/95899604-03479380-0dbb-11eb-8dc8-ab10bf572289.png)
![image](https://user-images.githubusercontent.com/3026584/95899645-0d699200-0dbb-11eb-9228-cb6b581ab363.png)

**Comment by pierosavi** [comment]
@minida28 
thanks for the quick feedback!

1. I'm aware of that and it's the main limitation that I was talking about
Some data is impossible to access directly like the metric list, I'm looking into a lightweight state manager to fix that in a nice stable way
2. Good catch, I missed that!

**Comment by HenrikRolandHansen** [comment]
Looking forward to the first release = me upgrading to grafana v7.x. 

Thanks for efforts and grate work.👍

**Comment by frdve** [comment]
Hi @pierosavi , also a big thank you for your great work!  I'm eagerly waiting for the plugin to be released!
I don't want to be pushy, but do you have a timeline when you will release the v1 to the store? 

Thanks!

**Comment by pierosavi** [comment]
> Hi @pierosavi , also a big thank you for your great work! I'm eagerly waiting for the plugin to be released!
> I don't want to be pushy, but do you have a timeline when you will release the v1 to the store?
> 
> Thanks!

Thanks for the kind words
Sadly I don't have a time, I am working on the last things to make it easier to use but the new Grafana changes make it kinda difficult to set up as it was before

**Comment by Juliuss11** [comment]
Hi @pierosavi , thanks for your plugin.
Can you please push on the repo also the built plugin (like for the official one) even if it is not completed? Would be easy for me to test it and provide feedback :)
Thanks,

**Comment by pierosavi** [comment]
@Juliuss11 Hi, pushing the built folder is against the new grafana sdk "rules" and can create problems in general

If you want to try building for yourself I updated the guide in the [README](https://github.com/pierosavi/pierosavi-imageit-panel/blob/react-migration/README.md) under **How to build** with the steps :)

**Comment by Juliuss11** [comment]
Hi @pierosavi , thanks a lot.
Untill now the plugin seems work fine.
One more feature that would be great for me is the possibility to define the size for each sensor instead of make it dependant to the font size.

**Comment by GarbatyGrabarz** [comment]
Hi, @pierosavi Your panel is amazing and I could not wait so I tried to build the plugin myself, however it does not show up on the plugins list (even after restart). Am I missing some obvious step? Im working on Raspberry Pi OS, could that be the reason? Besides bunch of linting errors building went smooth

**Comment by pierosavi** [comment]
Hi @GarbatyGrabarz thanks for the kind words! Please open a new issue indicating your Grafana version so I can help you better :)

**Comment by GarbatyGrabarz** [comment]
The sheer threat of opening a new issue made it work. I do not know what is this sorcery but I built it again and restarted the computer again and it worked. For clarification: the plugin showed up on the plugins list but not in the Visualization option. 
Thank you again @pierosavi for the amazing panel, and you, Digital Gods for blessing my components!

**Comment by pierosavi** [comment]
@GarbatyGrabarz Awesome! I will keep in mind praying the Digital Gods 🙏 next time it breaks

**Comment by G0nz0uk** [comment]
This plugin sounds amazing.  My goal is to upload our Visio server and network racks and show the equipment state as in green, amber or red (already have this in a Grafana table). 

When I link to my server-rack.png (http://x.x.x.x:3000/public/img/imageit/server-racks.png) under the unsigned imageit plugin section in the panel the image shows for a moment I get the error:

**An unexpected Error happened - TypeError: Cannot read property 'offsetWidth' of null**

Is it best I wait until the newer version is out?

**Comment by frdve** [comment]
@pierosavi, would it be possible to release the current version?  I have no access to the Grafana instance and cannot clone the repo to test the current version, but i'm very interested to test and use the current version of your plugin.  It's ok if there would still be an issue in the code, this can then be updated if needed.  

Thanks in advance!

**Comment by mirkocomparetti-synesis** [comment]
> @pierosavi, would it be possible to release the current version? I have no access to the Grafana instance and cannot clone the repo to test the current version, but i'm very interested to test and use the current version of your plugin. It's ok if there would still be an issue in the code, this can then be updated if needed.
> 
> Thanks in advance!

That would be important for us as well... we cannot clone the repository in the machine we are using and for now we have _broken_ dashboards and this packages is so appealing!
Thanks!

**Comment by kskenyon** [comment]
Can't get past the linter errors.  What can I do?

pierosavi-imageit-panel]$ yarn build
yarn run v1.22.10
$ grafana-toolkit plugin:build
✔ Preparing
⠙ Linting  
  
  
  /usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/src/Sensor.tsx
    83:27  error  Replace `·()·=>·setIsMouseOver(true)·` with `()·=>·setIsMouseOver(true)`    prettier/prettier
    84:27  error  Replace `·()·=>·setIsMouseOver(false)·` with `()·=>·setIsMouseOver(false)`  prettier/prettier
  
  /usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/src/CustomEditors/EditorMappingItem.tsx
     6:28  error  Insert `;`                                                                                                                                     prettier/prettier
     6:28  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    20:56  error  Insert `;`                                                                                                                                     prettier/prettier
    20:56  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    22:36  error  Insert `;`                                                                                                                                     prettier/prettier
    22:36  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    28:18  error  Replace `·index·+·1·` with `index·+·1`                                                                                                         prettier/prettier
    29:74  error  Replace `·()·=>·onDelete(index)·` with `()·=>·onDelete(index)`                                                                                 prettier/prettier
    36:39  error  Replace `·mapping.id·=·event.currentTarget.value·})` with `⏎··············mapping.id·=·event.currentTarget.value;⏎············});`             prettier/prettier
    36:78  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    36:81  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    45:39  error  Replace `·mapping.description·=·event.currentTarget.value` with `⏎··············mapping.description·=·event.currentTarget.value;⏎···········`  prettier/prettier
    45:87  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    55:39  error  Replace `·mapping.operator·=·selectableValue.value` with `⏎··············mapping.operator·=·selectableValue.value;⏎···········`                prettier/prettier
    55:80  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    64:39  error  Replace `·mapping.compareTo·=·event.currentTarget.value` with `⏎··············mapping.compareTo·=·event.currentTarget.value;⏎···········`      prettier/prettier
    64:85  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
    73:39  error  Replace `·mapping.values.fontColor·=·color` with `⏎··············mapping.values.fontColor·=·color;⏎···········`                                prettier/prettier
    73:72  error  Missing semicolon                                                                                                                              @typescript-eslint/semi
  
  ✖ 21 problems (21 errors, 0 warnings)
    21 errors and 0 warnings potentially fixable with the `--fix` option.
  
  
  
  Trace: Error: 21 linting errors found in 11 files
      at /usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/src/cli/tasks/plugin.build.js:117:31
      at step (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.next (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at fulfilled (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:107:62)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at /usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/src/cli/utils/useSpinner.js:24:29
      at step (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:136:27)
      at Object.throw (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:117:57)
      at rejected (/usr/share/grafana/public/app/plugins/panel/pierosavi-imageit-panel/node_modules/@grafana/toolkit/node_modules/tslib/tslib.js:108:69)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
✖ 21 linting errors found in 11 files
error Command failed with exit code 1.

**Comment by GarbatyGrabarz** [comment]
Manually fixing the linting issues worked for me

**Comment by kskenyon** [comment]
Thanks, I managed to fix the linting issues and it compiled OK.  However, as it happened to you, it doesn't show up as working in the Grafana Plugins panel with this error on a banner: 

"Error Loading Plugin
Check the server startup logs for more information. 
If this plugin was loaded from git, make sure it was compiled."

I did a few grafana-server.service restarts but no change. Nothing shows up in the logs indicating an error.  Grafana v7.3.6.

Stumped.

Kevin

**Comment by pierosavi** [comment]
Hi all, check out the new [README](https://github.com/pierosavi/pierosavi-imageit-panel/blob/react-migration/README.md) and let me know what you think. v1 is ready and will be published out as soon as the migration tool is ready, probably this week. @heliodor check out the features parity :)

**Comment by kskenyon** [comment]
Waiting with bated breath.  

Kevin

Fatfingered from my iPhone

**Comment by mirkocomparetti-synesis** [comment]
That is a great and big news!

Readme looks good to me and the fact that there is a way to host the image locally (with limitations) is a great news to me!

**Comment by frdve** [comment]
That is indeed superb news! 
The migration tool, is this something which will be triggered automatically when updating the plugin?

Thanks for the good work!

**Comment by pierosavi** [comment]
@frdve That will require a bit of manual work, pasting your panels JSON to a website and back again inside the panel

**Comment by mattbue** [comment]
Hi, today i tried this panel the first time and ran into the same error.
But great to see that the solution is coming.
Thanks!

**Comment by berilslv** [comment]
Fantastic news that this great plugin soon will work with newest grafana!
It will be possible to upgrade current version with simple cli command as 'grafana-cli plugins update-all' ?

**Comment by pierosavi** [comment]
@berilslv Yes, soon!
But, to keep data from the last version, you have to manually use the migrator tool when updating it (only for this major version update)
If not you'll just see empty ImageIt panels

**Comment by pierosavi** [comment]
v1 is in review!

Migrator and FAQ are live here
https://pierosavi.github.io/imageit-migration/

Waiting patiently with you for the release

**Comment by GarbatyGrabarz** [comment]
That is some amazing news! I was waiting for this day :) Great job!
Just to be clear. If I don't care about preserving my old panels I just need to update the plugin and I am good to go? Even if I built the plugin myself?

**Comment by mirkocomparetti-synesis** [comment]
Great news! 👍 
Hopefully the review will be quick and we will have the panel back soon! 😃
Thanks!

**Comment by HenrikRolandHansen** [comment]
Cool feature - grate job 👍

**Comment by frdve** [comment]
Great news!! Can't wait! :)

**Comment by pierosavi** [comment]
@GarbatyGrabarz Yep in that case just update it and that's it!

**Comment by nctuevamax** [comment]
So exciting! Hopefully to pass the release review soon. Thanks again for the great work!

**Comment by jajimgme** [comment]
Really needed this plugin for next week and how lucky! Thank you very much for your work!

**Comment by berilslv** [comment]
sorry for another bump, but is new version alive and ready to install/update?

**Comment by mirkocomparetti-synesis** [comment]
> sorry for another bump, but is new version alive and ready to install/update?

[Looks like the revision is not over yet](https://grafana.com/grafana/plugins/pierosavi-imageit-panel)

**Comment by frdve** [comment]
But it looks to be close.  The Pull Request of adding it to the Grafana plugin repository looks ready to be completed: https://github.com/grafana/grafana-plugin-repository/pull/835

**Comment by pierosavi** [comment]
Hi all
v1.0.0 is out!

Even better, 1.0.1 is out, already fixing a small issue on 1.0.0

Thanks for your patience, I'll close this veeery long issue and all the ones not related to this new version

**Comment by frdve** [comment]
Thank you very much for all the effort! :)
