### ISSUE TITLE
New Feature Request 3

### ISSUE THREAD

**Issue by ajaywazir** [pierosavi/pierosavi-imageit-panel#58]
Hi Piero
would it be possible to apply some math to metric values?
basic math, +,-, mul and div
For now using fixed values in text box,
in future may be another metric

Ajay

**Comment by heliodor** [comment]
Hi @ajaywazir , this is not something that should be implemented at the plugin level. Each plugin developer would have to implement this over and over. Solutions:
- Your data source most likely has the ability to perform mathematical calculations. Check your docs.
- If not, Grafana 7 allows you to do so using the new transformations functionality: https://grafana.com/docs/grafana/latest/panels/transformations/#add-field-from-calculation

**Comment by ajaywazir** [comment]
Hi Piero,
Thanks for clarifications
Noted on Grafana 7
Ajay

**Comment by pierosavi** [comment]
Thanks @heliodor for the correct answer, closing this
