### ISSUE TITLE
how to fetch metricValues in react plugin?

### ISSUE THREAD

**Issue by cs1193** [pierosavi/pierosavi-imageit-panel#59]
@pierosavi 

I am trying to build the react plugin where I am trying to retrieve the `metricValues`, but props are not giving this data. 

I am unsure how to trigger this `data-received` event.

Is there are way to populate the metrics dropdown with data? Any help is appreciated.

**Comment by pierosavi** [comment]
Hi @cs1193 , I'm not sure I understood the question, are you trying to get metrics data?
if so the data object from 
`export const ImageItPanel: React.FC<Props> = ({ options, data, width, height, onOptionsChange, fieldConfig }) => {
`
has metrics data
