### ISSUE TITLE
How does value/color mapping work ?

### ISSUE THREAD

**Issue by sharkyzz** [pierosavi/pierosavi-imageit-panel#6]
Hi,

Please see the screenshot below. I have only one sensor. What am I doing wrong ?

Thanks for your help!

![Screenshot 2019-04-13 at 10 26 12](https://user-images.githubusercontent.com/1429655/56076979-e5206200-5dd6-11e9-9792-d44de9ad2e04.png)

**Comment by pierosavi** [comment]
Hello,
That's the old version, update to the last version on master for the new mapping feature

**Comment by sharkyzz** [comment]
Did a checkout of master, but still doesn't seems to work. What am I doing wrong ?

![Screenshot 2019-04-13 at 13 32 35](https://user-images.githubusercontent.com/1429655/56079147-b1523600-5df0-11e9-8d58-c7806182c443.png)

**Comment by sharkyzz** [comment]
that did it, thanks
