### ISSUE TITLE
Issue manually installing React-Migration build

### ISSUE THREAD

**Issue by eyecee** [pierosavi/pierosavi-imageit-panel#60]
Hi Piero,

I'm running Grafana v7.3.1 (6668161a88) and after reading all the issues and comments with installing the ImageIt Panel v0.1.3 on Grafana 7.0.2+, I've tried to install the React-Migration build using the READ ME instructions but I got the following output:

$ sudo git clone --single-branch --branch react-migration git@github.com:pierosavi/pierosavi-imageit-panel.git
Cloning into 'pierosavi-imageit-panel'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Is there something I'm doing wrong? I've tried to download the source code directly from Github and then uploaded it to my server to then build with Yarn but I was also getting a 20+ errors on "yarn build" stage.

Thanks in advance!

**Comment by eyecee** [comment]
I managed to clone the react-migration branch via HTTPS so all good. Sorry for the inconvenience!

**Comment by pierosavi** [comment]
@eyecee sorry for ignoring, that was the correct way to fix, I updated the README

**Comment by eyecee** [comment]
Thanks @pierosavi - I appreciate the follow up and action. Cheers!
