### ISSUE TITLE
An unexpected Error happened - TypeError: Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by G0nz0uk** [pierosavi/pierosavi-imageit-panel#61]
This plugin sounds amazing. My goal is to upload our Visio server and network racks and show the equipment state as in green, amber or red (already have this in a Grafana table).

When I link to my server-rack.png (http://x.x.x.x:3000/public/img/imageit/server-racks.png) under the unsigned imageit plugin section in the panel the image shows for a moment I get the error:

An unexpected Error happened - TypeError: Cannot read property 'offsetWidth' of null

Is it best I wait until the newer version is out?

I'm using Grafana 7.3.1

Thanks

**Comment by frdve** [comment]
I think it's the same error as in #54, so I guess you have to wait until the new version comes out.
