### ISSUE TITLE
[Feature request]Changing color when treshhold reached

### ISSUE THREAD

**Issue by berilslv** [pierosavi/pierosavi-imageit-panel#67]
Hi Pierosavi,
Thanks for 1.0.1 update, it works really good!

I have question: 
Maybe there is possibility to set treshhold , and when its reached sensor color changes from green to red?

Thanks in advance! :)

**Comment by pierosavi** [comment]
That feature is already implemented, it's called mappings
Create a new mapping on the right menu and set its ID to the sensors that should be influenced by it
