### ISSUE TITLE
Multiple range operators don't seem to work

### ISSUE THREAD

**Issue by sharkyzz** [pierosavi/pierosavi-imageit-panel#7]
Hi,

I'm using the latest code, but multiple range operators don't seem to work. It doesn't take into account other range operators. See screenshots.

Thanks in advance for your help.

![Screenshot 2019-04-14 at 11 30 02](https://user-images.githubusercontent.com/1429655/56090980-431d7a00-5ea9-11e9-8fb1-11b55c5b75fc.png)
![Screenshot 2019-04-14 at 11 30 44](https://user-images.githubusercontent.com/1429655/56090984-457fd400-5ea9-11e9-8920-a238b7fb0216.png)

**Comment by pierosavi** [comment]
For multiple ranges it stops at the first one on the list that is actually true
So in your case on the sensor you should set High warking first, then High normal and then Low normal in this order :)

**Comment by sharkyzz** [comment]
Yes, that did it. Thanks a lot!
