### ISSUE TITLE
Feature request: Multiple mappings or operators support

### ISSUE THREAD

**Issue by GarbatyGrabarz** [pierosavi/pierosavi-imageit-panel#70]
I have an issue that one of the sensors should inform user if the values are outside of a range. I would like either to prepare two mappings (below and above value trigger) and feed a sensor two IDs or to be able to set double conditions for one mapping. I think the former could be more flexible for users.

Congrats on the latest release. It is amazing!

**Comment by dev592335** [comment]
We want to set background color to green, yellow or red depending on the value of a sensor (the value is actually based on the number of alarms for a node).
So we also would like to have multiple color mappings for a sensor.

**Comment by ellismendez** [comment]
+1 to multiple mappings for sensor. This would allow for something like green, yellow, red settings for different sensor ranges.

**Comment by vernazza** [comment]
Agree. I'm using this for temperature sensors and with the old version I had different levels with different colors, which made the situation clear with just a sight

**Comment by cfotnz** [comment]
@pierosavi can we have [this PR](https://github.com/pierosavi/pierosavi-imageit-panel/pull/98) released soon?

**Comment by pierosavi** [comment]
This feature is in the next version 1.0.5, currently in review by the grafana team, it usually takes a week to be reviewed and released
