### ISSUE TITLE
Metric Value 0 showed as No Data

### ISSUE THREAD

**Issue by Francesco-30** [pierosavi/pierosavi-imageit-panel#75]
**Describe the bug**
A sensor associated with a query shows "No data" instead of "0" when the query return a numeric or boolean "0" value

**To Reproduce**
1. Set a datasource (I tried both Postgres 10 and influxdb)
2. Create a new v1.0.1 imageIt panel
3. Set a query for a metric that can admit 0 as a value (eg. outdoor temperature can be 0, a boolean can be 0)
4. create a sensor associated to the query 

**Expected behavior**
The sensor text box should show 0 when the queried metric value is 0

**Screenshots**
![immagine](https://user-images.githubusercontent.com/62717088/108732646-0ce1c480-752e-11eb-8ab4-8ed3e74d0679.png)
![immagine](https://user-images.githubusercontent.com/62717088/108732789-2c78ed00-752e-11eb-878d-026c9dd6d64d.png)

**Grafana (please complete the following information):**
 - Firefox or Chrome
 - Plugin Version 1.0.1
 - Grafana 7.0.2

**Additional context**
Using Grafana Query inspector I see that the query correctly returns 0 value for the metric.
Thanks for the support

**Comment by nuthub** [comment]
I can confirm this bug with Grafana v7.4.3 and Plugin v1.0.1

**Comment by berilslv** [comment]
I there any hot-fix or workaround for this bug?

**Comment by pierosavi** [comment]
https://github.com/pierosavi/pierosavi-imageit-panel/issues/69
