### ISSUE TITLE
Still not able to load the plugin.

### ISSUE THREAD

**Issue by kskenyon** [pierosavi/pierosavi-imageit-panel#76]
I removed the old one I installed from git and installed the new one using grafana-cli.  

I still get the

**Error loading: pierosavi-imageit-panel**

Any ideas on how to get the plugin going?  I could really use it.

Grafana Version 7.4.2 (commit: 29e75ad97b, branch: HEAD)

**Comment by pierosavi** [comment]
Hi do you still have that error?

**Comment by kskenyon** [comment]
It won’t work with Safari but it does work with Chrome. Not sure what the problem is. 

Kevin

Fatfingered from my iPhone

**Comment by kskenyon** [comment]
Working OK now in Safari after latest updates to MacOS and Grafana.

Kevin
