### ISSUE TITLE
Missing signature

### ISSUE THREAD

**Issue by ThoWoKi** [pierosavi/pierosavi-imageit-panel#92]
**Describe the bug**

**To Reproduce**
1. Go to 'Configuration --> Plugins'
pierosavi-imageit-panel - Missing signature

**Expected behavior**
Plugin needs to be updated to work with Grafana 8.0

**Screenshots**

![2021-06-11 13_55_29-Window](https://user-images.githubusercontent.com/3208396/121682750-c1432e80-cabc-11eb-8d3c-6cb9f7c11de8.png)

**Grafana (please complete the following information):**
 - Browser [e.g. chrome, safari] --> Chrome
 - Plugin Version [e.g. 1.0.1] --> 1.0.3
 - Grafana Version [e.g. 7.3.6] --> 8.0.0

**Additional context**
Plugin can not be loaded due to "missing Signature" in Grafana 8.0.0

**Comment by pierosavi** [comment]
Thank you, I pushed an update to Grafana review
